### ISSUE TITLE
cannot find the the usb device in /dev

### ISSUE THREAD

**Issue by javajax** [technomancy/atreus-firmware#34]
I am trying to update the software on the atreus and having a little bit of trouble.

I have unplugged the keyboard and run `ls /dev > /tmp/dev-off`
Then plunged the keyboard back in and used it to make sure it worked and run `ls /dev > /tmp/dev-on`.
Then I ran a diff with `diff /tmp/dev-off /tmp/dev-on` and got no diffs.

I have tried to take down a few variants to see what could be the problem including doing this while running `make upload` and not but I cannot figure it out.

Also the keyboard is currently working I just want to update the software.

Any help would be great.

Cheers,
Jack

**Comment by technomancy** [comment]
Sorry for the trouble you're having here.

I think the confusion might be specifically around the bootloader
mode. The board will not accept a new firmware upload unless it has
entered "bootloader mode" by being reset. Simply plugging it in is not
enough.

The main way to enter bootloader mode is to trigger it with a key
binding--hitting the enter key while in layer 2 should do the
trick. However, as a backup you can do a hard reset to enter the
bootloader by touching the RST and GND pins together twice in under a
second. This requires removing the back plate, obviously.

You can tell when you're in bootloader mode because the LED will pulse
gently. (Again, only visible with the case open.) Note that it only
stays in bootloader mode for 8 seconds.

Let me know if that clears things up.

**Comment by javajax** [comment]
So in testing this I had reinstalled "avrdude" with the flag --with-usb and it worked first time.

I think at some point I had cleaned up brew and untaped the "larsimmisch/avr" repository and uninstalled "avrdude" and reinstalled it under "osx-cross/avr" and the default flags must have changed

All of this is a guess but it works now.

Cheers,
Jack

**Comment by technomancy** [comment]
Glad to hear you got it working now.
