### ISSUE TITLE
Unable to  generate layout html on Debian & Ubuntu

### ISSUE THREAD

**Issue by abhas** [technomancy/atreus-firmware#37]
I have been trying to generate the html layout on Ubuntu and Debian for many days now but it just doesn't seem to work. The error I get is:

    layercount = 3
    layer 0
    sed: can't read : No such file or directory

This error shows up at the start of each layer that the script processes. I tried to debug the script but couldn't localise the issue. The resulting HTML looks like this:

![atreus-layout-error](https://cloud.githubusercontent.com/assets/255701/10971687/7d5f4540-83fb-11e5-8d47-15039a2f541c.png)

Just to be on the safe side, I ran this in a clean Debian Jessie Docker container but the results are the same.

**Comment by technomancy** [comment]
Sorry, the SVG output stuff was contributed by a user and has been
rather neglected since. I have been considering just deleting it.

However, in this case the xNNNx problem you're seeing was an easy fix,
so I just pushed that out. The script is still a bit of a mess with some
of the other keycodes, but it looks a lot better.
