### ISSUE TITLE
Esc key causes reset

### ISSUE THREAD

**Issue by manyids2** [technomancy/atreus-firmware#52]
Dear technomancy,

Thank you for your excellent software. I used a Teensy 2, with the qwerty layout and was able to properly upload the firmware. It seems to almost work perfectly, except that the ESC key causes the Teensy to go into programming mode, and the TAB key does not work. Is there any way to debug such issues and rectify it?

**Comment by technomancy** [comment]
> Thank you for your excellent software. I used a Teensy 2, with the
> qwerty layout and was able to properly upload the firmware. It seems
> to almost work perfectly, except that the ESC key causes the Teensy to
> go into programming mode.

In earlier revisions I had hard-coded the ESC key to go to the
bootloader mode because sometimes there would be bugs in the
layer-switching code, so it was impossible to reach the regular reset.

However, that's all been commented out, so I don't know how it's
possible that it's happening now, unless you are running a very old
revision.

In any case, I would recommend using the QMK firmware instead of this
one; as you have noticed it has a few bugs and isn't very well polished.

-Phil

**Comment by manyids2** [comment]
Thank you for the prompt reply! I used QMK and now everything is perfect and most excellent. Thank you so very much!
